apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hello-world
  labels:
    app: fastapi-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-hello-world
  template:
    metadata:
      labels:
        app: fastapi-hello-world
    spec:
      containers:
      - name: fastapi-hello-world
        image: link2coryACR.azurecr.io/fastapi-hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: fastapi-hello-world
